CREATE DATABASE F1SimulatorDBTeamManegementService
GO
USE F1SimulatorDBTeamManegementService
GO
CREATE TABLE Teams(
    TeamId UNIQUEIDENTIFIER PRIMARY KEY  NOT NULL,
    [Name] VARCHAR(50) NOT NULL,
    NameAcronym VARCHAR(10) NOT NULL,
    Country VARCHAR(50) NOT NULL
);
CREATE TABLE Boss(
    BossId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    TeamId UNIQUEIDENTIFIER NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Age INT NOT NULL
);
CREATE TABLE Engineers(
    EngineerId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    TeamId UNIQUEIDENTIFIER NOT NULL,
    CarId UNIQUEIDENTIFIER NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
	ExperienceFactor NUMERIC(5, 3) NOT NULL,
    Specialization VARCHAR(2)
    CHECK (Specialization IN ('Ca', 'Cp')) NOT NULL
);
CREATE TABLE Cars(
    CarId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    TeamId UNIQUEIDENTIFIER NOT NULL,
    Model Char(5) NOT NULL,
    WeightKg NUMERIC(6,2) NOT NULL,
    Speed INTEGER NOT NULL,
    Ca NUMERIC(4,3) NOT NULL,
    Cp NUMERIC(4,3) NOT NULL
);
CREATE TABLE [Drivers] (
	DriverId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	DriverNumber VARCHAR(2) UNIQUE NOT NULL,
	TeamId UNIQUEIDENTIFIER NOT NULL,
	CarId UNIQUEIDENTIFIER NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	FullName VARCHAR(50) NOT NULL,
	ExperienceFactor NUMERIC(5, 3) NOT NULL,
	WeightKg NUMERIC(5,2) NOT NULL,
	HandiCap NUMERIC(5,2) NOT NULL
);
ALTER TABLE [Engineers]
ADD FOREIGN KEY([TeamId])
REFERENCES [Teams]([TeamId])
GO
ALTER TABLE [Boss]
ADD FOREIGN KEY([TeamId])
REFERENCES [Teams]([TeamId])
GO
ALTER TABLE [Cars]
ADD FOREIGN KEY([TeamID])
REFERENCES [Teams]([TeamId])
GO
ALTER TABLE [Drivers]
ADD FOREIGN KEY([TeamId])
REFERENCES [Teams]([TeamId])
GO
ALTER TABLE [Drivers]
ADD FOREIGN KEY([CarId])
REFERENCES [Cars]([CarId])
GO
ALTER TABLE [Engineers]
ADD FOREIGN KEY([CarId])
REFERENCES [Cars]([CarId])
GO
ALTER TABLE Engineers
ADD CONSTRAINT UQ_Car_Specialization
UNIQUE (CarId, Specialization);
GO
CREATE DATABASE F1SimulatorDBCompetitionService;
GO
USE F1SimulatorDBCompetitionService
GO
CREATE TABLE Season(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Year] INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT 0
);
GO
CREATE TABLE Races(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Round] INT  NOT NULL,
	[Status] VARCHAR(20) NOT NULL,
	SeasonId UNIQUEIDENTIFIER NOT NULL,
	CircuitId UNIQUEIDENTIFIER NOT NULL,
	T1 BIT NOT NULL,
	T2 BIT NOT NULL,
	T3 BIT NOT NULL,
    Qualifier BIT NOT NULL,
	Race BIT NOT NULL
);
GO
CREATE TABLE Circuits(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] VARCHAR(150) NOT NULL,
	Country VARCHAR(150) NOT NULL,
	LapsNumber INT NOT NULL
);
GO
CREATE TABLE DriverStandings(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	SeasonId UNIQUEIDENTIFIER NOT NULL,
	DriverName VARCHAR(150) NOT NULL,
	DriverId UNIQUEIDENTIFIER NOT NULL,
	TeamId UNIQUEIDENTIFIER NOT NULL,
	Points DECIMAL(10,2) NOT NULL
);
GO
CREATE TABLE TeamStandings(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	SeasonId UNIQUEIDENTIFIER NOT NULL,
	TeamName VARCHAR(150) NOT NULL,
	TeamId UNIQUEIDENTIFIER NOT NULL,
	Points DECIMAL(10,2) NOT NULL
);
GO
ALTER TABLE Races
ADD CONSTRAINT FK_Races_Seasons
FOREIGN KEY (SeasonId) REFERENCES Season(Id);
GO
ALTER TABLE Races
ADD CONSTRAINT FK_Races_Circuits
FOREIGN KEY (CircuitId) REFERENCES Circuits(Id);
GO
ALTER TABLE DriverStandings
ADD CONSTRAINT FK_DriverStandings_Season
FOREIGN KEY (SeasonId) REFERENCES Season(Id);
GO
ALTER TABLE TeamStandings
ADD CONSTRAINT FK_TeamStandings_Season
FOREIGN KEY (SeasonId) REFERENCES Season(Id);